repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
releases:
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    values:
    - kube_prometheus_stack_values.yaml
  - name: loki-stack
    namespace: monitoring
    chart: grafana/loki-stack
