version: '3.2'
services:
  caddy:
    image: abiosoft/caddy
    volumes:
      - '$PWD/Caddyfile:/etc/Caddyfile'
      - '$HOME/.caddy:/root/.caddy'
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
  client:
    image: dubov94/keyring-client
  grpc-gateway:
    image: 'bazel/grpc_gateway:grpc_gateway'
  server:
    image: 'bazel/server:server'
    secrets:
      - mailgun_api_key
    environment:
      GEOLOCATION_SERVICE_ENDPOINT: 'ip-geolocation:80'
  ip-geolocation:
    image: dubov94/keyring-ip-geolocation
  postgres:
    image: 'postgres:10'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keyring
    volumes:
      - '/root/postgres:/var/lib/postgresql/data'
  redis:
    image: redis
    volumes:
      - '/root/redis:/data'
secrets:
  mailgun_api_key:
    external: true
