version: '3.2'
services:
  caddy:
    image: abiosoft/caddy
    volumes:
      - '$PWD/Caddyfile:/etc/Caddyfile'
      - '$HOME/.caddy:/root/.caddy'
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
  client:
    image: dubov94/keyring-client
  gateway:
    image: dubov94/keyring-gateway
    environment:
      PROXY_TARGET: 'server:591'
  server:
    image: dubov94/keyring-server
    secrets:
      - mailgun_api_key
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keyring
    volumes:
      - '/root/postgres:/var/lib/postgresql/data'
  redis:
    image: redis
    volumes:
      - '/root/redis:/data'
secrets:
  mailgun_api_key:
    external: true
