version: '3.2'
services:
  reverse-proxy:
    image: 'bazel:reverse_proxy'
    volumes:
      - '$HOME/.caddy:/root/.caddy'
    ports:
      - '80:80'
      - '443:443'
  pwa:
    image: 'bazel/pwa:pwa'
  grpc-gateway:
    image: 'bazel/grpc_gateway:grpc_gateway'
  server:
    image: 'bazel/server:server'
    secrets:
      - mailgun_api_key
  ip-geolocation:
    image: 'bazel/ip_geolocation:ip_geolocation'
    secrets:
      - geoipupdate_account_id
      - geoipupdate_license_key
  postgres:
    image: 'postgres:10'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keyring
    volumes:
      - '/root/postgres:/var/lib/postgresql/data'
  redis:
    image: redis
    volumes:
      - '/root/redis:/data'
secrets:
  mailgun_api_key:
    external: true
  geoipupdate_account_id:
    external: true
  geoipupdate_license_key:
    external: true
