version: '3.2'
services:
  client:
    image: dubov94/keyring-client
    ports:
      - '81:80'
  gateway:
    image: dubov94/keyring-gateway
    environment:
      PROXY_TARGET: 'server:591'
    ports:
      - '82:80'
  server:
    image: dubov94/keyring-server
    ports:
      - '591'
    secrets:
      - mailgun_api_key
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keyring
    volumes:
      - '/root/postgres:/var/lib/postgresql/data'
  redis:
    image: redis
    volumes:
      - '/root/redis:/data'
secrets:
  mailgun_api_key:
    external: true
