java_library(
    name = "user_projection",
    srcs = ["UserProjection.java"],
    visibility = ["//server/src/main/java/com/floreina/keyring/interceptors:__pkg__"],
    deps = ["//server/src/main/java/com/floreina/keyring/entities:user"],
)
