resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi
deschedulerPolicy:
  profiles:
    - name: default
      pluginConfig:
      - name: LowNodeUtilization
        args:
          thresholds:
            memory: 44
          targetThresholds:
            memory: 48
      plugins:
        balance:
          enabled:
            - LowNodeUtilization
