postgresql:
  existingSecret: postgres-postgresql-ha-postgresql
  replicaCount: 3
  database: keyring
  syncReplication: true
  # `bitnami/postgresql-ha` is susceptible to split-brain, see
  # https://github.com/bitnami/charts/issues/20998. Switch to
  # cloudnative-pg.io or CockroachDB (heavier).
  repmgrFenceOldPrimary: true
persistence:
  enabled: true
  size: 2Gi
pgpool:
  existingSecret: postgres-postgresql-ha-pgpool
  replicaCount: 1
  resources:
    limits:
      memory: 256Mi
