postgresql:
  existingSecret: postgres-postgresql-ha-postgresql
  replicaCount: 3
  database: keyring
  syncReplication: true
persistence:
  enabled: true
  size: 2Gi
pgpool:
  existingSecret: postgres-postgresql-ha-pgpool
  replicaCount: 2
  resources:
    limits:
      memory: 192Mi
