apiVersion: batch/v1
kind: CronJob
metadata:
  name: janitor-cronjob
  labels:
    app.kubernetes.io/name: janitor
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: janitor
        spec:
          containers:
          - name: janitor
            image: dubov94/keyring-janitor
            imagePullPolicy: Always
            env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          restartPolicy: OnFailure
