java_library(
    name = "chronometry",
    srcs = ["Chronometry.java"],
)

java_library(
    name = "cryptography",
    srcs = ["Cryptography.java"],
    deps = ["@maven//:com_google_guava_guava"],
)

java_library(
    name = "environment",
    srcs = ["Environment.java"],
)
