load("//bazel/workspace:substitution.bzl", "status_vars_template")

status_vars_template(
    name = "mrgn_version",
    output = "mrgn_version.txt",
    template = "mrgn_version.tmpl.txt",
    visibility = ["//server:internal"],
)
