-- liquibase formatted sql

-- changeset liquibase:1
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_schema = 'public' and table_name = 'keys'
CREATE TABLE "public"."keys" (
    "identifier" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "creation_timestamp" TIMESTAMP WITHOUT TIME ZONE,
    "is_shadow" BOOLEAN DEFAULT FALSE,
    "labels" TEXT [],
    "value" TEXT,
    "version" BIGINT NOT NULL,
    "parent_identifier" BIGINT,
    "user_identifier" BIGINT,
    CONSTRAINT "keys_pkey" PRIMARY KEY ("identifier")
);

-- changeset liquibase:2
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_schema = 'public' and table_name = 'mail_tokens'
CREATE TABLE "public"."mail_tokens" (
    "identifier" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "attempt_count" INTEGER DEFAULT 0,
    "code" TEXT,
    "last_attempt" TIMESTAMP WITHOUT TIME ZONE DEFAULT '1970-01-01 00:00:00',
    "mail" TEXT,
    "timestamp" TIMESTAMP WITHOUT TIME ZONE,
    "version" BIGINT NOT NULL,
    "user_identifier" BIGINT,
    CONSTRAINT "mail_tokens_pkey" PRIMARY KEY ("identifier")
);

-- changeset liquibase:3
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_schema = 'public' and table_name = 'otp_params'
CREATE TABLE "public"."otp_params" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "creation_timestamp" TIMESTAMP WITHOUT TIME ZONE,
    "scratch_codes" TEXT [],
    "shared_secret" TEXT,
    "user_identifier" BIGINT,
    CONSTRAINT "otp_params_pkey" PRIMARY KEY ("id")
);

-- changeset liquibase:4
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_schema = 'public' and table_name = 'otp_tokens'
CREATE TABLE "public"."otp_tokens" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "creation_timestamp" TIMESTAMP WITHOUT TIME ZONE,
    "is_initial" BOOLEAN,
    "value" TEXT,
    "user_identifier" BIGINT,
    CONSTRAINT "otp_tokens_pkey" PRIMARY KEY ("id")
);

-- changeset liquibase:5
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_schema = 'public' and table_name = 'sessions'
CREATE TABLE "public"."sessions" (
    "identifier" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "client_version" TEXT,
    "ip_address" TEXT,
    "key" TEXT,
    "timestamp" TIMESTAMP WITHOUT TIME ZONE,
    "user_agent" TEXT,
    "user_identifier" BIGINT,
    CONSTRAINT "sessions_pkey" PRIMARY KEY ("identifier")
);

-- changeset liquibase:6
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_schema = 'public' and table_name = 'users'
CREATE TABLE "public"."users" (
    "identifier" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "hash" TEXT,
    "last_session" TIMESTAMP WITHOUT TIME ZONE,
    "mail" TEXT,
    "otp_shared_secret" TEXT,
    "otp_spare_attempts" INTEGER DEFAULT 0,
    "salt" TEXT,
    "state" INTEGER,
    "timestamp" TIMESTAMP WITHOUT TIME ZONE,
    "username" TEXT,
    "version" BIGINT NOT NULL,
    CONSTRAINT "users_pkey" PRIMARY KEY ("identifier")
);

-- changeset liquibase:7
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.table_constraints where table_schema = 'public' and table_name = 'otp_tokens' and constraint_name = 'ukepg9lkm4ggrlj2daic3l3i2vw'
ALTER TABLE
    "public"."otp_tokens"
ADD
    CONSTRAINT "ukepg9lkm4ggrlj2daic3l3i2vw" UNIQUE ("user_identifier", "value");

-- changeset liquibase:8
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.table_constraints where table_schema = 'public' and table_name = 'users' and constraint_name = 'uk_r43af9ap4edm43mmtq01oddj6'
ALTER TABLE
    "public"."users"
ADD
    CONSTRAINT "uk_r43af9ap4edm43mmtq01oddj6" UNIQUE ("username");

-- changeset liquibase:9
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_schema = 'public' and table_name = 'feature_prompts'
CREATE TABLE "public"."feature_prompts" (
    "fuzzy_search" BOOLEAN,
    "otp" BOOLEAN,
    "version" BIGINT NOT NULL,
    "user_identifier" BIGINT NOT NULL,
    CONSTRAINT "feature_prompts_pkey" PRIMARY KEY ("user_identifier")
);

-- changeset liquibase:10
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.table_constraints where table_schema = 'public' and table_name = 'otp_tokens' and constraint_name = 'fk1u2jwse5b3wdxuvhk37jwtaxp'
ALTER TABLE
    "public"."otp_tokens"
ADD
    CONSTRAINT "fk1u2jwse5b3wdxuvhk37jwtaxp" FOREIGN KEY ("user_identifier") REFERENCES "public"."users" ("identifier") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:11
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.table_constraints where table_schema = 'public' and table_name = 'mail_tokens' and constraint_name = 'fk4bho6q1wvhvj71c4mlboqc2we'
ALTER TABLE
    "public"."mail_tokens"
ADD
    CONSTRAINT "fk4bho6q1wvhvj71c4mlboqc2we" FOREIGN KEY ("user_identifier") REFERENCES "public"."users" ("identifier") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:12
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.table_constraints where table_schema = 'public' and table_name = 'otp_params' and constraint_name = 'fk4n8xrfcqrlgwfbmkxqw28e6u0'
ALTER TABLE
    "public"."otp_params"
ADD
    CONSTRAINT "fk4n8xrfcqrlgwfbmkxqw28e6u0" FOREIGN KEY ("user_identifier") REFERENCES "public"."users" ("identifier") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:13
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.table_constraints where table_schema = 'public' and table_name = 'keys' and constraint_name = 'fk9bpkeay3gjqgj6qsh1usbmkwe'
ALTER TABLE
    "public"."keys"
ADD
    CONSTRAINT "fk9bpkeay3gjqgj6qsh1usbmkwe" FOREIGN KEY ("user_identifier") REFERENCES "public"."users" ("identifier") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:14
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.table_constraints where table_schema = 'public' and table_name = 'sessions' and constraint_name = 'fkm4okt87wyku2rji43sd4yrkym'
ALTER TABLE
    "public"."sessions"
ADD
    CONSTRAINT "fkm4okt87wyku2rji43sd4yrkym" FOREIGN KEY ("user_identifier") REFERENCES "public"."users" ("identifier") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:15
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.table_constraints where table_schema = 'public' and table_name = 'keys' and constraint_name = 'fko76l9bbtm9ne8jkl824tx8oub'
ALTER TABLE
    "public"."keys"
ADD
    CONSTRAINT "fko76l9bbtm9ne8jkl824tx8oub" FOREIGN KEY ("parent_identifier") REFERENCES "public"."keys" ("identifier") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:16
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.table_constraints where table_schema = 'public' and table_name = 'feature_prompts' and constraint_name = 'fkstt2d96538kdhgl2qhiouhep3'
ALTER TABLE
    "public"."feature_prompts"
ADD
    CONSTRAINT "fkstt2d96538kdhgl2qhiouhep3" FOREIGN KEY ("user_identifier") REFERENCES "public"."users" ("identifier") ON UPDATE NO ACTION ON DELETE CASCADE;
