-- liquibase formatted sql

-- changeset liquibase:1
CREATE TABLE "public"."keys" (
    "identifier" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "creation_timestamp" TIMESTAMP WITHOUT TIME ZONE,
    "is_shadow" BOOLEAN DEFAULT FALSE,
    "labels" TEXT [],
    "value" TEXT,
    "version" BIGINT NOT NULL,
    "parent_identifier" BIGINT,
    "user_identifier" BIGINT,
    CONSTRAINT "keys_pkey" PRIMARY KEY ("identifier")
);

-- changeset liquibase:2
CREATE TABLE "public"."mail_tokens" (
    "identifier" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "code" TEXT,
    "mail" TEXT,
    "timestamp" TIMESTAMP WITHOUT TIME ZONE,
    "user_identifier" BIGINT,
    CONSTRAINT "mail_tokens_pkey" PRIMARY KEY ("identifier")
);

-- changeset liquibase:3
CREATE TABLE "public"."otp_params" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "creation_timestamp" TIMESTAMP WITHOUT TIME ZONE,
    "scratch_codes" TEXT [],
    "shared_secret" TEXT,
    "user_identifier" BIGINT,
    CONSTRAINT "otp_params_pkey" PRIMARY KEY ("id")
);

-- changeset liquibase:4
CREATE TABLE "public"."otp_tokens" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "creation_timestamp" TIMESTAMP WITHOUT TIME ZONE,
    "is_initial" BOOLEAN,
    "value" TEXT,
    "user_identifier" BIGINT,
    CONSTRAINT "otp_tokens_pkey" PRIMARY KEY ("id")
);

-- changeset liquibase:5
CREATE TABLE "public"."sessions" (
    "identifier" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "client_version" TEXT,
    "ip_address" TEXT,
    "key" TEXT,
    "timestamp" TIMESTAMP WITHOUT TIME ZONE,
    "user_agent" TEXT,
    "user_identifier" BIGINT,
    CONSTRAINT "sessions_pkey" PRIMARY KEY ("identifier")
);

-- changeset liquibase:6
CREATE TABLE "public"."users" (
    "identifier" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "hash" TEXT,
    "last_session" TIMESTAMP WITHOUT TIME ZONE,
    "mail" TEXT,
    "otp_shared_secret" TEXT,
    "otp_spare_attempts" INTEGER DEFAULT 0,
    "salt" TEXT,
    "state" INTEGER,
    "timestamp" TIMESTAMP WITHOUT TIME ZONE,
    "username" TEXT,
    "version" BIGINT NOT NULL,
    CONSTRAINT "users_pkey" PRIMARY KEY ("identifier")
);

-- changeset liquibase:7
ALTER TABLE
    "public"."mail_tokens"
ADD
    CONSTRAINT "ukr4rty43bw9ypv2lhopckw6xt0" UNIQUE ("user_identifier", "code");

-- changeset liquibase:8
ALTER TABLE
    "public"."otp_tokens"
ADD
    CONSTRAINT "ukepg9lkm4ggrlj2daic3l3i2vw" UNIQUE ("user_identifier", "value");

-- changeset liquibase:9
ALTER TABLE
    "public"."users"
ADD
    CONSTRAINT "uk_r43af9ap4edm43mmtq01oddj6" UNIQUE ("username");

-- changeset liquibase:10
CREATE TABLE "public"."feature_prompts" (
    "fuzzy_search" BOOLEAN,
    "otp" BOOLEAN,
    "version" BIGINT NOT NULL,
    "user_identifier" BIGINT NOT NULL,
    CONSTRAINT "feature_prompts_pkey" PRIMARY KEY ("user_identifier")
);

-- changeset liquibase:11
ALTER TABLE
    "public"."otp_tokens"
ADD
    CONSTRAINT "fk1u2jwse5b3wdxuvhk37jwtaxp" FOREIGN KEY ("user_identifier") REFERENCES "public"."users" ("identifier") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:12
ALTER TABLE
    "public"."mail_tokens"
ADD
    CONSTRAINT "fk4bho6q1wvhvj71c4mlboqc2we" FOREIGN KEY ("user_identifier") REFERENCES "public"."users" ("identifier") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:13
ALTER TABLE
    "public"."otp_params"
ADD
    CONSTRAINT "fk4n8xrfcqrlgwfbmkxqw28e6u0" FOREIGN KEY ("user_identifier") REFERENCES "public"."users" ("identifier") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:14
ALTER TABLE
    "public"."keys"
ADD
    CONSTRAINT "fk9bpkeay3gjqgj6qsh1usbmkwe" FOREIGN KEY ("user_identifier") REFERENCES "public"."users" ("identifier") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:15
ALTER TABLE
    "public"."sessions"
ADD
    CONSTRAINT "fkm4okt87wyku2rji43sd4yrkym" FOREIGN KEY ("user_identifier") REFERENCES "public"."users" ("identifier") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:16
ALTER TABLE
    "public"."keys"
ADD
    CONSTRAINT "fko76l9bbtm9ne8jkl824tx8oub" FOREIGN KEY ("parent_identifier") REFERENCES "public"."keys" ("identifier") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:17
ALTER TABLE
    "public"."feature_prompts"
ADD
    CONSTRAINT "fkstt2d96538kdhgl2qhiouhep3" FOREIGN KEY ("user_identifier") REFERENCES "public"."users" ("identifier") ON UPDATE NO ACTION ON DELETE CASCADE;
