export const SESSION_LIFETIME_IN_MILLIS = 5 * 60 * 1000
export const HALF_SESSION_IN_MILLIS = SESSION_LIFETIME_IN_MILLIS / 2

export const SESSION_TOKEN_HEADER_NAME = 'X-Session-Token'

export const CLIENT_VERSION_HEADER_NAME = 'X-Client-Version'
