apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwa-deployment
  labels:
    app.kubernetes.io/name: pwa
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pwa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pwa
    spec:
      containers:
      - name: pwa
        image: dubov94/keyring-pwa:b10890de011418ee3272814a8b85c424d52b7e3c
        ports:
        - containerPort: 8080
