apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwa-deployment
  labels:
    app.kubernetes.io/name: pwa
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pwa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pwa
    spec:
      containers:
      - name: pwa
        image: dubov94/keyring-pwa:06925232b06805c33532c2337960e2ebfe05029a
        ports:
        - containerPort: 8080
