apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwa-deployment
  labels:
    app.kubernetes.io/name: pwa
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pwa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pwa
    spec:
      containers:
      - name: pwa
        image: dubov94/keyring-pwa:c5f0318c012d01c8f65f337b9e839c7eb5eeb8d4
        ports:
        - containerPort: 8080
