apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirection-deployment
  labels:
    app.kubernetes.io/name: redirection
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redirection
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redirection
    spec:
      containers:
      - name: redirection
        image: dubov94/keyring-redirection:69454ff9bfdf9d0dbe0919b312fd7f411779635a
        ports:
        - containerPort: 8080
