java_library(
    name = "annotations",
    srcs = ["Annotations.java"],
    visibility = ["//server/src/main/java/com/floreina/keyring/storage:__pkg__"],
    deps = ["//server/src/main/java/com/floreina/keyring/entities:user"],
)
