exports_files([
    "deactivation_notice_body.md.pebble",
    "deactivation_notice_head.text.pebble",
    "mail_vc_body.md.pebble",
    "mail_vc_head.text.pebble",
    "uncompleted_authn_body.md.pebble",
    "uncompleted_authn_head.text.pebble",
])
