exports_files([
    "deactivation_notice_body.md.twig",
    "deactivation_notice_head.text.twig",
    "mail_vc_body.md.twig",
    "mail_vc_head.text.twig",
    "uncompleted_authn_body.md.twig",
    "uncompleted_authn_head.text.twig",
])
