name: HTTP-to-GRPC

on:
  push:
    branches:
      - master

jobs:
  grpc_gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mishas/setup-bazelisk-action@v1
      - run: bazelisk run //grpc_gateway
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - run: docker image tag bazel/grpc_gateway:grpc_gateway docker.io/dubov94/keyring-grpc-gateway
      - run: docker push docker.io/dubov94/keyring-grpc-gateway
