name: PWA

on:
  push:
    branches:
      - master

jobs:
  pwa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mishas/setup-bazelisk-action@v1
      - run: bazel test $(bazel query 'tests(//pwa/...)')
