name: PWA

on:
  push:
    branches:
      - master

jobs:
  pwa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mishas/setup-bazelisk-action@v1
      - uses: actions/cache@v2
        with:
          path: '~/.cache/bazel'
          key: bazel
      - run: bazel test $(bazel query 'tests(//pwa/...)')
